server:
  port: 9090

  servlet:
    session:
      timeout: 5m

spring:

  application:
    name: StoreLink

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/storelink
    username: postgres
    password: "0110"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

#  data:
#    mongodb: 
#      uri: ${MONGODB_URI}
#      database: storelink
  config:
    import:
      - optional:file:.env[.properties]

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

image:
  upload:
   dir: uploads


#logging:
#  level:
#    root: DEBUG

logging:
  level:
    com:
      storelink: INFO
    