server:
  port: 9090

  servlet:
    session:
      timeout: 5m

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/storelink
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    mongodb: 
      uri: ${MONGODB_URI}
      database: storelink
  config:
    import:
      - optional:file:.env[.properties]


#logging:
#  level:
#    root: DEBUG

#logging:
#  level:
#    com:
#      storelink: ERROR
    