server:
  port: 9090

  servlet:
    session:
      timeout: 5m

spring:

  application:
    name: StoreLink

  datasource:
    url: jdbc:mysql://localhost:3306/storelink
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    mongodb: 
      uri: ${MONGODB_URI}
      database: storelink
  config:
    import:
      - optional:file:.env[.properties]


  mail:
    host: smtp.gmail.com
    port: 587
    username: shaon42hridoy@gmail.com
    password: bneineggtbpipanu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

image:
  upload:
   dir: uploads


#logging:
#  level:
#    root: DEBUG

#logging:
#  level:
#    com:
#      storelink: ERROR
    